# Generated by Django 2.2.6 on 2019-12-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price_per_item',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.Product'),
        ),
    ]
