# Generated by Django 2.2.6 on 2019-11-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191106_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='countryoforigin',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
