# Generated by Django 2.2.6 on 2019-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191106_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foto',
            field=models.ImageField(default='static/media/author_images/placeholder.png', upload_to='static/media/author_images/'),
        ),
    ]
