# Generated by Django 2.2.6 on 2019-11-06 23:14

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_author_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=False, on=('product',)),
        ),
    ]
