# Generated by Django 2.2.6 on 2019-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191107_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='countryoforigin',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='defoult_slug', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Язык'),
        ),
    ]
